// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYJfrqxUG4gsCRLFU3vgL5dGVa6-U1D8I',
    appId: '1:272476438327:web:ef66735dcf03d37025a4b2',
    messagingSenderId: '272476438327',
    projectId: 'personal-project-39fa9',
    authDomain: 'personal-project-39fa9.firebaseapp.com',
    storageBucket: 'personal-project-39fa9.appspot.com',
    measurementId: 'G-0P0XXB3TEB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9wFzv6KMuQzwlWr4K3Z08ooWVqHqPVeY',
    appId: '1:272476438327:android:a1ee23e235c1acb825a4b2',
    messagingSenderId: '272476438327',
    projectId: 'personal-project-39fa9',
    storageBucket: 'personal-project-39fa9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT_rGv_uX9Cj3VhFf-m1oujnC7c6yPWH8',
    appId: '1:272476438327:ios:f24b28390f9aa34825a4b2',
    messagingSenderId: '272476438327',
    projectId: 'personal-project-39fa9',
    storageBucket: 'personal-project-39fa9.appspot.com',
    iosBundleId: 'com.example.flutterApplicationFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT_rGv_uX9Cj3VhFf-m1oujnC7c6yPWH8',
    appId: '1:272476438327:ios:f24b28390f9aa34825a4b2',
    messagingSenderId: '272476438327',
    projectId: 'personal-project-39fa9',
    storageBucket: 'personal-project-39fa9.appspot.com',
    iosBundleId: 'com.example.flutterApplicationFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYJfrqxUG4gsCRLFU3vgL5dGVa6-U1D8I',
    appId: '1:272476438327:web:27b810f3328f478c25a4b2',
    messagingSenderId: '272476438327',
    projectId: 'personal-project-39fa9',
    authDomain: 'personal-project-39fa9.firebaseapp.com',
    storageBucket: 'personal-project-39fa9.appspot.com',
    measurementId: 'G-EM2BQD2R0C',
  );
}
